---
#
# add users and SSH keys

- hosts: webservers
  gather_facts: True
  vars_files:
    - all.yml
  remote_user: root
  tasks:

  - name: Gathering user info
    local_action: command whoami
    register: youruser

  - name: Setup a system user
    user: name=exampleuser
          shell=/sbin/nologin
          generate_ssh_key=yes
          ssh_key_bits=2048
          ssh_key_file=.ssh/id_rsa

  - name: Add your SSH publickey to authorized keys
    authorized_key:
      user=exampleuser
      key="{{ lookup('file','/home/{{youruser.stdout}}/.ssh/id_rsa.pub')}}"
      manage_dir=yes
    ignore_errors: true

  - name: Add other SSH public keys
    authorized_key:
      user=exampleuser
      key="{{ lookup('file','authorized_keys')}}"
