---

- hosts: webservers
  gather_facts: True
  remote_user: root
  vars_files:
     - all.yml
  tasks:

  - name: Import EPEL GPG Key
    rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
      state=present
    become: true

  - name: Check for EPEL repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state=present
    become: true

  - name: Install Package Dependencies
    yum: name={{ item }} state=present
    become: true
    with_items:
      - screen
      - htop
